services:
  - type: web
    name: floww-ai
    env: python
    pythonVersion: 3.10
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn mime_ai.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mime_ai.settings
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: mermaid-ai.onrender.com
      - key: CHROMA_DB_PATH
        value: /data/chroma
      - key: HF_HOME
        value: /data/huggingface
      - key: TRANSFORMERS_CACHE
        value: /data/huggingface/models
